"""
SEMANTIC ANALYSIS: not_executable/skipped → no_action

Traces the two different no_action paths through the state machine.
"""

print('SEMANTIC ANALYSIS')
print('='*60)
print()
print('PATH 1 — Policy no_action (guardrail blocks):')
print('  _node_guardrail: prob < 0.3')
print('  transition_case(id, "no_action", reason="Recovery prob X pct below minimum")')
print('  from_state in audit log: "deciding"')
print('  final_status = "no_action"')
print()
print('PATH 2 — Executor not_executable (Smart Retry):')
print('  _node_decide: failure=UPI_TIMEOUT -> action = "Smart Retry"')
print('  _node_guardrail: PASSES (prob is fine, amount is fine)')
print('  _node_execute: transition_case("recovering"), calls execute_recovery("Smart Retry")')
print('  execute_recovery returns: {status: "not_executable", ...}')
print('  _node_verify: exec_status == "not_executable"')
print('  transition_case(id, "verifying")  -- already done in _node_verify line 275')
print('  THEN transition_case(id, "no_action", reason="Cannot be retried...")')
print('  from_state in audit log: "verifying"')
print('  final_status = "no_action"')
print()
print('PATH 3 — Executor skipped (WAIT):')
print('  Same as PATH 2 but exec_status == "skipped"')
print('  Also transitions from "verifying" -> "no_action"')
print()
print('WHAT IS COLLAPSED:')
print('  recovery_cases.status = "no_action" in ALL three cases')
print('  No "not_executable" or "skipped" states exist at the DB case level')
print()
print('WHAT IS PRESERVED (only in audit table):')
print('  recovery_case_transitions.from_state:')
print('    Policy: deciding -> no_action')
print('    Executor: verifying -> no_action')
print('  recovery_case_transitions.reason:')
print('    Policy: "Recovery probability X pct below minimum (30%) - no action"')
print('    Executor: "Standard checkout payments cannot be retried via API..."')
print()
print('ADDITIONAL ISSUE:')
print('  PATH 2 visits "recovering" before "no_action".')
print('  This means a Smart Retry UPI_TIMEOUT case will be:')
print('    detected -> analyzing -> predicting -> deciding -> approved')
print('    -> recovering -> verifying -> no_action')
print('  The AUDIT TRAIL shows the case went through "recovering" before "no_action".')
print('  This is semantically unusual (it entered the execution phase then did nothing),')
print('  but NOT an invalid transition since:')
print('    recovering -> verifying is valid')
print('    verifying -> no_action is valid (added in Step 4)')
print()
print('VERDICT ON SEMANTIC COLLAPSE:')
print('  The collapse of not_executable/skipped -> no_action at the business state level')
print('  is a KNOWN DESIGN CHOICE for Step 4 because the state machine has no')
print('  "not_executable" or "skipped" terminal states. The distinction is preserved')
print('  in the audit trail (recovery_case_transitions) via from_state + reason.')
print('  This is recoverable by Step 5 / Step 10 if needed.')
